<script lang="ts">
  import { onMount } from 'svelte';
  import placeholder from './placeholder.svg';
  import { boundedPoint, defaultDock, dockPoint, keyboardDock, snapDock, type DockPosition, type Viewport } from './dock.ts';
  import { clipPlan, nextFrame, type ClipPlan } from './playback.ts';
  type Activity = 'idle' | 'thinking' | 'read' | 'work' | 'replying' | 'success' | 'concern'; export let activity: Activity; export let label: string;
  const key = 'her.pet-dock.v1'; let host: HTMLDivElement; let position: DockPosition; let live: { x: number; y: number } | undefined; let dragging = false; let origin = { x: 0, y: 0 }; let pointerOffset = { x: 0, y: 0 }; let moved = false;
  let scene: { setActivity: (activity: Activity) => Promise<void> } | undefined;
  const view = (): Viewport => ({ width: innerWidth, height: innerHeight, size: Math.min(160, Math.max(96, innerWidth * .12)) }); const visual = () => live ?? dockPoint(position ?? defaultDock(view()), view()); const style = () => { const p = visual(); return `left:${p.x}px;top:${p.y}px`; };
  function save() { try { localStorage.setItem(key, JSON.stringify(position)); } catch {} }
  function down(e: PointerEvent) { const p = visual(); dragging = true; moved = false; origin = { x: e.clientX, y: e.clientY }; pointerOffset = { x: e.clientX - p.x, y: e.clientY - p.y }; host.setPointerCapture(e.pointerId); }
  function move(e: PointerEvent) { if (!dragging) return; const p = boundedPoint({ x: e.clientX - pointerOffset.x, y: e.clientY - pointerOffset.y }, view()); if (Math.hypot(e.clientX-origin.x, e.clientY-origin.y) > 8) { moved = true; live = p; e.preventDefault(); } }
  function up(e: PointerEvent) { if (dragging && moved) { position = snapDock(live ?? { x: e.clientX, y: e.clientY }, view()); save(); } live = undefined; dragging = false; }
  function keyboard(e: KeyboardEvent) { const next = keyboardDock(position ?? defaultDock(view()), e.key, view()); if (!next) return; e.preventDefault(); position = next; save(); }
  $: if (scene) void scene.setActivity(activity);
  onMount(() => { let app: import('pixi.js').Application | undefined; let disposed = false; void (async () => { try { const parsed = JSON.parse(localStorage.getItem(key) ?? ''); if (['left','right','top','bottom'].includes(parsed.edge) && Number.isFinite(parsed.offset)) position = parsed; } catch {} position ??= defaultDock(view()); const pixi = await import('pixi.js'); if (disposed) return; app = new pixi.Application({ width: 256, height: 256, backgroundAlpha: 0, antialias: true }); host.replaceChildren(app.view as HTMLCanvasElement); const sprite = new pixi.Sprite(); sprite.width = 256; sprite.height = 256; app.stage.addChild(sprite); let texture: import('pixi.js').Texture | undefined; let plan: ClipPlan = { frameCount: 8, fps: 8, loop: true }; let frame = 0; let elapsed = 0; let request = 0; const reduced = matchMedia('(prefers-reduced-motion: reduce)').matches;
      scene = { async setActivity(next) { const token = ++request; const response = await fetch(`/api/pet-assets/${next}`, { cache: 'no-store' }); const source = response.ok ? response.url : placeholder; const loaded = await pixi.Assets.load(source); if (disposed || token !== request) return; texture = loaded; plan = response.ok ? clipPlan(response.headers) : { frameCount: 8, fps: 8, loop: true }; frame = 0; elapsed = 0; sprite.texture.destroy(false); sprite.texture = new pixi.Texture(loaded.baseTexture, new pixi.Rectangle(0, 0, loaded.width / plan.frameCount, loaded.height)); } };
      await scene.setActivity(activity); if (!reduced) app.ticker.add(() => { if (!texture) return; elapsed += app!.ticker.deltaMS; const next = nextFrame(frame, elapsed, plan); if (next === frame) return; elapsed = 0; frame = next; sprite.texture.destroy(false); sprite.texture = new pixi.Texture(texture.baseTexture, new pixi.Rectangle(frame * (texture.width / plan.frameCount), 0, texture.width / plan.frameCount, texture.height)); }); })(); return () => { disposed = true; scene = undefined; app?.destroy(true, { children: true, texture: false, baseTexture: false }); }; });
</script>
<div bind:this={host} class:dragging class="pet-dock" style={style()} data-activity={activity} role="button" tabindex="0" aria-label={label} on:pointerdown={down} on:pointermove={move} on:pointerup={up} on:pointercancel={up} on:keydown={keyboard}></div>
<style>.pet-dock{position:fixed;z-index:40;width:clamp(96px,12vw,160px);height:clamp(96px,12vw,160px);touch-action:none;cursor:grab;outline-offset:4px}.pet-dock.dragging{cursor:grabbing}.pet-dock:focus-visible{outline:3px solid var(--color-primary,#3b82f6);border-radius:50%}.pet-dock :global(canvas){width:100%;height:100%;display:block;pointer-events:none}@media(max-width:360px),(max-height:480px){.pet-dock{width:96px;height:96px}}</style>
